# Generated by Django 5.1.3 on 2024-12-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posudek",
            name="vydani",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prispevky",
                to="journal_app.vydani",
            ),
        ),
        migrations.AlterField(
            model_name="prispevekhistory",
            name="vydani",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prispevky_history",
                to="journal_app.vydani",
            ),
        ),
    ]
