# Generated by Django 5.1.3 on 2024-11-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0005_alter_posudek_stav_alter_prispevek_stav"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posudek",
            name="stav",
            field=models.CharField(
                choices=[("prirazeno", "Prirazeno"), ("odeslano", "Odesláno")],
                default="prirazeno",
                max_length=20,
            ),
        ),
    ]
