# Generated by Django 5.1.3 on 2024-11-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0006_alter_posudek_stav"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posudek",
            name="stav",
            field=models.CharField(
                choices=[("prirazeno", "Přiřazeno"), ("odeslano", "Odesláno")],
                default="prirazeno",
                max_length=20,
            ),
        ),
    ]
