# Generated by Django 5.1.3 on 2024-12-12 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0007_alter_posudek_stav"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sefredaktor",
            fields=[
                (
                    "uzivatel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [("can_read_agenda", "Can read agenda")],
            },
            bases=("journal_app.uzivatel",),
        ),
        migrations.CreateModel(
            name="Vydani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cislo", models.IntegerField()),
                ("tema", models.CharField(max_length=255)),
                ("date", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="prispevekhistory",
            name="vydani",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prispevky",
                to="journal_app.vydani",
            ),
        ),
    ]
