# Generated by Django 5.1.3 on 2024-12-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0008_sefredaktor_vydani_prispevekhistory_vydani"),
    ]

    operations = [
        migrations.AddField(
            model_name="vydani",
            name="stav",
            field=models.CharField(
                choices=[("pripravuje_se", "Připravuje se"), ("vydano", "Vydáno")],
                default="pripravuje_se",
                max_length=20,
            ),
        ),
    ]
