# Generated by Django 5.1.3 on 2024-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0009_vydani_stav"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vydani",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
