# Generated by Django 5.1.3 on 2024-11-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="autor",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="uzivatel",
            managers=[],
        ),
    ]
