# Generated by Django 5.1.3 on 2024-11-15 23:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0003_alter_prispevek_datum_podani"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recenzent",
            fields=[
                (
                    "uzivatel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [("can_send_posudek", "Can review")],
            },
            bases=("journal_app.uzivatel",),
        ),
        migrations.CreateModel(
            name="Redaktor",
            fields=[
                (
                    "uzivatel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("oblast_expertizy", models.CharField(max_length=100)),
            ],
            options={
                "permissions": [
                    ("can_assign_posudek", "Can assign a review to a Recenzent")
                ],
            },
            bases=("journal_app.uzivatel",),
        ),
        migrations.CreateModel(
            name="Posudek",
            fields=[
                ("posudek_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "originalita_hodnoceni",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "odbornost_hodnoceni",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "jazykova_uroven_hodnoceni",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "prispevek_hodnoceni",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("otevrena_zpetna_vazba", models.TextField(blank=True, null=True)),
                ("datum_posudku", models.DateField(blank=True, null=True)),
                (
                    "stav",
                    models.CharField(
                        choices=[("koncept", "Koncept"), ("odeslano", "Odesláno")],
                        default="koncept",
                        max_length=20,
                    ),
                ),
                (
                    "prispevek",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posudky",
                        to="journal_app.prispevek",
                    ),
                ),
                (
                    "recenzent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posudky",
                        to="journal_app.recenzent",
                    ),
                ),
                (
                    "redaktor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posudky",
                        to="journal_app.redaktor",
                    ),
                ),
            ],
        ),
    ]
