# Generated by Django 5.1.3 on 2024-11-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0004_recenzent_redaktor_posudek"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posudek",
            name="stav",
            field=models.CharField(
                choices=[("prirazeno", "Prirazeno"), ("odeslano", "Odesláno")],
                default="koncept",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prispevek",
            name="stav",
            field=models.CharField(
                choices=[
                    ("koncept", "Koncept"),
                    ("poslano_k_recenzi", "Poslano k recenzi"),
                    ("v_recenzi", "V recenzi"),
                    ("odmitnut", "Odmítnut"),
                    ("prijat", "Přijat"),
                ],
                default="koncept",
                max_length=20,
            ),
        ),
    ]
